name: CI/CD [pull_request]

on:
  pull_request:
    branches: [main]

jobs:
  run-checks:
    runs-on: ubuntu-20.04
    name: Run checks 🤖
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: PNPM install
        run: pnpm install --frozen-lockfile
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
      - name: Run TS check
        run: pnpm type-check
      - name: Run ESLint
        run: pnpm lint
      - name: Run Unit Tests
        run: pnpm test:ci
      - name: Run build
        run: pnpm build
      - name: Install Playwright dependencies
        run: pnpm playwright install --with-deps
      - name: Run e2e tests
        run: pnpm test:e2e
